// /app/layout.js
import { Geist, Geist_Mono } from "next/font/google"
import SidebarLayout from '@/components/SidebarLayout'
import Providers from "@/lib/providers"
import { Toaster } from "sonner"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <SidebarLayout>
            {children}
            <Toaster
              position="top-right"
              richColors
              closeButton
              toastOptions={{
                className: "bg-background text-foreground",
                style: {
                  fontFamily: "var(--font-geist-sans)",
                },
              }}
            />
          </SidebarLayout>
        </Providers>
      </body>
    </html>
  )
}
